### ISSUE TITLE
ERROR Disk error while locking directory /kafka

### ISSUE THREAD

**Issue by sangmook-ai** [jingene/fastcampus_kafka_handson#1]
실습을 따라하고 있는데 이런 오류가 뜨네요

kafka-3_1      | [2021-12-24 06:02:19,711] ERROR Disk error while locking directory /kafka (kafka.server.LogDirFailureChannel)
kafka-3_1      | java.nio.file.AccessDeniedException: /kafka/.lock
kafka-3_1      | 	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
kafka-3_1      | 	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
kafka-3_1      | 	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
kafka-3_1      | 	at java.base/sun.nio.fs.UnixFileSystemProvider.newFileChannel(UnixFileSystemProvider.java:182)
kafka-3_1      | 	at java.base/java.nio.channels.FileChannel.open(FileChannel.java:292)
kafka-3_1      | 	at java.base/java.nio.channels.FileChannel.open(FileChannel.java:345)
kafka-3_1      | 	at kafka.utils.FileLock.<init>(FileLock.scala:31)
kafka-3_1      | 	at kafka.log.LogManager.$anonfun$lockLogDirs$1(LogManager.scala:231)
kafka-3_1      | 	at scala.collection.StrictOptimizedIterableOps.flatMap(StrictOptimizedIterableOps.scala:117)
kafka-3_1      | 	at scala.collection.StrictOptimizedIterableOps.flatMap$(StrictOptimizedIterableOps.scala:104)
kafka-3_1      | 	at scala.collection.mutable.ArraySeq.flatMap(ArraySeq.scala:37)
kafka-3_1      | 	at kafka.log.LogManager.lockLogDirs(LogManager.scala:229)
kafka-3_1      | 	at kafka.log.LogManager.<init>(LogManager.scala:106)
kafka-3_1      | 	at kafka.log.LogManager$.apply(LogManager.scala:1238)
kafka-3_1      | 	at kafka.server.KafkaServer.startup(KafkaServer.scala:249)
kafka-3_1      | 	at kafka.Kafka$.main(Kafka.scala:109)
kafka-3_1      | 	at kafka.Kafka.main(Kafka.scala)
kafka-3_1      | [2021-12-24 06:02:19,715] ERROR [KafkaServer id=3] Fatal error during KafkaServer startup. Prepare to shutdown (kafka.server.KafkaServer)
kafka-3_1      | java.nio.file.AccessDeniedException: /kafka/recovery-point-offset-checkpoint
kafka-3_1      | 	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
kafka-3_1      | 	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
kafka-3_1      | 	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
kafka-3_1      | 	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219)
kafka-3_1      | 	at java.base/java.nio.file.Files.newByteChannel(Files.java:371)
kafka-3_1      | 	at java.base/java.nio.file.Files.createFile(Files.java:648)
kafka-3_1      | 	at kafka.server.checkpoints.CheckpointFile.<init>(CheckpointFile.scala:87)
kafka-3_1      | 	at kafka.server.checkpoints.OffsetCheckpointFile.<init>(OffsetCheckpointFile.scala:65)
kafka-3_1      | 	at kafka.log.LogManager.$anonfun$recoveryPointCheckpoints$1(LogManager.scala:108)
kafka-3_1      | 	at scala.collection.StrictOptimizedIterableOps.map(StrictOptimizedIterableOps.scala:99)
kafka-3_1      | 	at scala.collection.StrictOptimizedIterableOps.map$(StrictOptimizedIterableOps.scala:86)
kafka-3_1      | 	at scala.collection.mutable.ArraySeq.map(ArraySeq.scala:37)
kafka-3_1      | 	at kafka.log.LogManager.<init>(LogManager.scala:107)
kafka-3_1      | 	at kafka.log.LogManager$.apply(LogManager.scala:1238)
kafka-3_1      | 	at kafka.server.KafkaServer.startup(KafkaServer.scala:249)
kafka-3_1      | 	at kafka.Kafka$.main(Kafka.scala:109)
kafka-3_1      | 	at kafka.Kafka.main(Kafka.scala)
kafka-3_1      | [2021-12-24 06:02:19,716] INFO [KafkaServer id=3] shutting down (kafka.server.KafkaServer)
kafka-3_1      | [2021-12-24 06:02:19,718] INFO [feature-zk-node-event-process-thread]: Shutting down (kafka.server.FinalizedFeatureChangeListener$ChangeNotificationProcessorThread)
kafka-3_1      | [2021-12-24 06:02:19,718] INFO [feature-zk-node-event-process-thread]: Shutdown completed (kafka.server.FinalizedFeatureChangeListener$ChangeNotificationProcessorThread)
kafka-3_1      | [2021-12-24 06:02:19,718] INFO [feature-zk-node-event-process-thread]: Stopped (kafka.server.FinalizedFeatureChangeListener$ChangeNotificationProcessorThread)
kafka-3_1      | [2021-12-24 06:02:19,719] INFO [ZooKeeperClient Kafka server] Closing. (kafka.zookeeper.ZooKeeperClient)

docker compose로 컨테이너를 까는데 kafka가 안 깔리는 것 같습니다. 
환경은 ubuntu 20.04.3 LTS이고 docker 20.10.12입니다.

**Comment by jaeykweon** [comment]
이거 권한 문제일겁니다
sudo chmod 777 -R /kafka 해보세요

**Comment by jingene** [comment]
안녕하세요~
윗분 말씀처럼 directory 권한 이슈인것 같은데요. 여전히 문제가 해결되지 않으신다면 fckafkaqna@gmail.com 으로 메일 주시기 바랍니다.

감사합니다!
